apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-restaurant
  namespace: restaurant
  labels:
    app: api-restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-restaurant
  template:
    metadata:
      labels:
        app: api-restaurant
      namespace: restaurant
    spec:
      containers:
        - name: api-restaurant
          image: tiesta/asm_restaurant_api:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: restaurant-db-config-map
                  key: mysql_server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: restaurant-db-config-map
                  key: mysql-database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: restaurant-db-config-map
                  key: mysql-user-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-restaurant-pass
                  key: mysql-user-password
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: restaurant-app-cm
                  key: rabbitHost
            - name: RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  name: restaurant-app-cm
                  key: rabbitPort
            - name: RABBIT_USER
              valueFrom:
                configMapKeyRef:
                  name: restaurant-app-cm
                  key: rabbitUser
            - name: RABBIT_PSSWD
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: rabbitPsswd