
package wsdl.cloud.romanellas.joliebank;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import xsd.cloud.romanellas.joliebank.AccountInfo;
import xsd.cloud.romanellas.joliebank.ObjectFactory;
import xsd.cloud.romanellas.joliebank.TransactionInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BANK_GATEWAY_2", targetNamespace = "joliebank.romanellas.cloud.wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BANKGATEWAY2 {


    /**
     * 
     * @param msg
     * @param cvv
     * @param expireMonth
     * @param accId
     * @param pan
     * @param expireYear
     * @param status
     */
    @WebMethod(action = "postCreateCard")
    @RequestWrapper(localName = "postCreateCard", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PostCreateCard")
    @ResponseWrapper(localName = "postCreateCardResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PostCreateCardResponse")
    public void postCreateCard(
        @WebParam(name = "cvv", targetNamespace = "")
        int cvv,
        @WebParam(name = "expire_month", targetNamespace = "")
        int expireMonth,
        @WebParam(name = "expire_year", targetNamespace = "")
        int expireYear,
        @WebParam(name = "pan", targetNamespace = "")
        String pan,
        @WebParam(name = "acc_id", targetNamespace = "")
        int accId,
        @WebParam(name = "msg", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> msg,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> status);

    /**
     * 
     * @param amount
     * @param code
     * @param beneficiary
     * @param token
     * @param status
     */
    @WebMethod(action = "getCheckPay")
    @RequestWrapper(localName = "getCheckPay", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.GetCheckPay")
    @ResponseWrapper(localName = "getCheckPayResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.GetCheckPayResponse")
    public void getCheckPay(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "amount", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Double> amount,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> code,
        @WebParam(name = "beneficiary", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> beneficiary,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> status);

    /**
     * 
     * @param code
     * @param token
     * @param status
     */
    @WebMethod(action = "deletePay")
    @RequestWrapper(localName = "deletePay", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.DeletePay")
    @ResponseWrapper(localName = "deletePayResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.DeletePayResponse")
    public void deletePay(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> code,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> status);

    /**
     * 
     * @param msg
     * @param token
     * @param status
     */
    @WebMethod(action = "putNotRefaundable")
    @RequestWrapper(localName = "putNotRefaundable", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PutNotRefaundable")
    @ResponseWrapper(localName = "putNotRefaundableResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PutNotRefaundableResponse")
    public void putNotRefaundable(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "msg", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> msg,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> status);

    /**
     * 
     * @param exists
     * @param account
     * @param status
     */
    @WebMethod(action = "getAccountExists")
    @RequestWrapper(localName = "getAccountExists", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.GetAccountExists")
    @ResponseWrapper(localName = "getAccountExistsResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.GetAccountExistsResponse")
    public void getAccountExists(
        @WebParam(name = "account", targetNamespace = "")
        int account,
        @WebParam(name = "exists", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> exists,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> status);

    /**
     * 
     * @param owner
     * @return
     *     returns int
     */
    @WebMethod(action = "postAccount")
    @WebResult(name = "identifier", targetNamespace = "")
    @RequestWrapper(localName = "postAccount", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PostAccount")
    @ResponseWrapper(localName = "postAccountResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PostAccountResponse")
    public int postAccount(
        @WebParam(name = "owner", targetNamespace = "")
        String owner);

    /**
     * 
     * @param amount
     * @param destAccount
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "postPay")
    @WebResult(name = "token", targetNamespace = "")
    @RequestWrapper(localName = "postPay", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PostPay")
    @ResponseWrapper(localName = "postPayResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PostPayResponse")
    public String postPay(
        @WebParam(name = "amount", targetNamespace = "")
        double amount,
        @WebParam(name = "dest_account", targetNamespace = "")
        int destAccount);

    /**
     * 
     * @param page
     * @return
     *     returns java.util.List<xsd.cloud.romanellas.joliebank.AccountInfo>
     */
    @WebMethod(action = "getAccount")
    @WebResult(name = "array", targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.GetAccountResponse")
    public List<AccountInfo> getAccount(
        @WebParam(name = "page", targetNamespace = "")
        int page);

    /**
     * 
     * @param accId
     * @param page
     * @return
     *     returns java.util.List<xsd.cloud.romanellas.joliebank.TransactionInfo>
     */
    @WebMethod(action = "getTransactions")
    @WebResult(name = "array", targetNamespace = "")
    @RequestWrapper(localName = "getTransactions", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.GetTransactions")
    @ResponseWrapper(localName = "getTransactionsResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.GetTransactionsResponse")
    public List<TransactionInfo> getTransactions(
        @WebParam(name = "page", targetNamespace = "")
        int page,
        @WebParam(name = "acc_id", targetNamespace = "")
        int accId);

    /**
     * 
     * @param amount
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "putWithdraw")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "putWithdraw", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PutWithdraw")
    @ResponseWrapper(localName = "putWithdrawResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PutWithdrawResponse")
    public String putWithdraw(
        @WebParam(name = "amount", targetNamespace = "")
        int amount,
        @WebParam(name = "account", targetNamespace = "")
        int account);

    /**
     * 
     * @param cvv
     * @param code
     * @param expireMonth
     * @param cardHolderLastName
     * @param pan
     * @param expireYear
     * @param cardHolderFirstName
     * @param token
     * @param status
     */
    @WebMethod(action = "putPay")
    @RequestWrapper(localName = "putPay", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PutPay")
    @ResponseWrapper(localName = "putPayResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PutPayResponse")
    public void putPay(
        @WebParam(name = "cvv", targetNamespace = "")
        int cvv,
        @WebParam(name = "expire_month", targetNamespace = "")
        int expireMonth,
        @WebParam(name = "card_holder_first_name", targetNamespace = "")
        String cardHolderFirstName,
        @WebParam(name = "expire_year", targetNamespace = "")
        int expireYear,
        @WebParam(name = "pan", targetNamespace = "")
        String pan,
        @WebParam(name = "card_holder_last_name", targetNamespace = "")
        String cardHolderLastName,
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "code", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> code,
        @WebParam(name = "status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> status);

    /**
     * 
     * @param amount
     * @param account
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "putDeposit")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "putDeposit", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PutDeposit")
    @ResponseWrapper(localName = "putDepositResponse", targetNamespace = "joliebank.romanellas.cloud", className = "xsd.cloud.romanellas.joliebank.PutDepositResponse")
    public String putDeposit(
        @WebParam(name = "amount", targetNamespace = "")
        int amount,
        @WebParam(name = "account", targetNamespace = "")
        int account);

}
