
package wsdl.cloud.romanellas.joliebank;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BANK_GATEWAY_2Service", targetNamespace = "joliebank.romanellas.cloud.wsdl", wsdlLocation = "file:/home/romanellas/WebstormProjects/ASMProject/bank/src/static/content/gateway.wsdl")
public class BANKGATEWAY2Service
    extends Service
{

    private final static URL BANKGATEWAY2SERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKGATEWAY2SERVICE_EXCEPTION;
    private final static QName BANKGATEWAY2SERVICE_QNAME = new QName("joliebank.romanellas.cloud.wsdl", "BANK_GATEWAY_2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/romanellas/WebstormProjects/ASMProject/bank/src/static/content/gateway.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKGATEWAY2SERVICE_WSDL_LOCATION = url;
        BANKGATEWAY2SERVICE_EXCEPTION = e;
    }

    public BANKGATEWAY2Service() {
        super(__getWsdlLocation(), BANKGATEWAY2SERVICE_QNAME);
    }

    public BANKGATEWAY2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKGATEWAY2SERVICE_QNAME, features);
    }

    public BANKGATEWAY2Service(URL wsdlLocation) {
        super(wsdlLocation, BANKGATEWAY2SERVICE_QNAME);
    }

    public BANKGATEWAY2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKGATEWAY2SERVICE_QNAME, features);
    }

    public BANKGATEWAY2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BANKGATEWAY2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BANKGATEWAY2
     */
    @WebEndpoint(name = "BANK_GATEWAY_2ServicePort")
    public BANKGATEWAY2 getBANKGATEWAY2ServicePort() {
        return super.getPort(new QName("joliebank.romanellas.cloud.wsdl", "BANK_GATEWAY_2ServicePort"), BANKGATEWAY2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BANKGATEWAY2
     */
    @WebEndpoint(name = "BANK_GATEWAY_2ServicePort")
    public BANKGATEWAY2 getBANKGATEWAY2ServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("joliebank.romanellas.cloud.wsdl", "BANK_GATEWAY_2ServicePort"), BANKGATEWAY2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKGATEWAY2SERVICE_EXCEPTION!= null) {
            throw BANKGATEWAY2SERVICE_EXCEPTION;
        }
        return BANKGATEWAY2SERVICE_WSDL_LOCATION;
    }

}
