
package org.w3._2001.xmlschema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BANK_GATEWAYService", targetNamespace = "http://www.w3.org/2001/XMLSchema.wsdl", wsdlLocation = "file:/home/romanellas/WebstormProjects/ASMProject/bank/src/static/content/gateway.wsdl")
public class BANKGATEWAYService
    extends Service
{

    private final static URL BANKGATEWAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKGATEWAYSERVICE_EXCEPTION;
    private final static QName BANKGATEWAYSERVICE_QNAME = new QName("http://www.w3.org/2001/XMLSchema.wsdl", "BANK_GATEWAYService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/romanellas/WebstormProjects/ASMProject/bank/src/static/content/gateway.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKGATEWAYSERVICE_WSDL_LOCATION = url;
        BANKGATEWAYSERVICE_EXCEPTION = e;
    }

    public BANKGATEWAYService() {
        super(__getWsdlLocation(), BANKGATEWAYSERVICE_QNAME);
    }

    public BANKGATEWAYService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKGATEWAYSERVICE_QNAME, features);
    }

    public BANKGATEWAYService(URL wsdlLocation) {
        super(wsdlLocation, BANKGATEWAYSERVICE_QNAME);
    }

    public BANKGATEWAYService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKGATEWAYSERVICE_QNAME, features);
    }

    public BANKGATEWAYService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BANKGATEWAYService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BANKGATEWAY
     */
    @WebEndpoint(name = "BANK_GATEWAYServicePort")
    public BANKGATEWAY getBANKGATEWAYServicePort() {
        return super.getPort(new QName("http://www.w3.org/2001/XMLSchema.wsdl", "BANK_GATEWAYServicePort"), BANKGATEWAY.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BANKGATEWAY
     */
    @WebEndpoint(name = "BANK_GATEWAYServicePort")
    public BANKGATEWAY getBANKGATEWAYServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.w3.org/2001/XMLSchema.wsdl", "BANK_GATEWAYServicePort"), BANKGATEWAY.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKGATEWAYSERVICE_EXCEPTION!= null) {
            throw BANKGATEWAYSERVICE_EXCEPTION;
        }
        return BANKGATEWAYSERVICE_WSDL_LOCATION;
    }

}
