apiVersion: v1
kind: Service
metadata:
  name: apiuser-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: apiuser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
