apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  containers:
  - name: mysql-client
    image: mysql:8
    command: ['sleep', '3600']  # Tienilo vivo per poterci entrare
  restartPolicy: Never
