apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data:
  mysql-server: mysql_courier       # The name of mysql service
  mysql-database-name: CourierDB    # The name of the database used by the app
  mysql-user-username: user         # A user fot app 