apiVersion: v1
kind: Service
metadata:
  name: mysql-courier
  labels:
    app: mysql-courier
spec:
  type: NodePort  # Solo per sviluppo locale con Minikube
  ports:
    - port: 3306
  selector:
    app: mysql-courier
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql-courier
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-courier
  labels:
    app: mysql-courier
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql-courier
  template:
    metadata:
      labels:
        app: mysql-courier
    spec:
      containers:
      - name: mysql
        image: docker.io/tiesta/asm_courier_db:0.10
        ports:
        - containerPort: 3306
          name: mysql
        livenessProbe:
          tcpSocket:
            port: 3306
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
