FROM node:alpine
WORKDIR /app
COPY *.json ./

COPY ./src ./src
RUN npm install
RUN npm install -g @angular/cli

EXPOSE 4200

# CMD ["ng", "serve", "--proxy-config", "proxy.config.json", "--host","0.0.0.0"] -> for dev env
CMD ["ng", "serve", "--proxy-config", "proxy.config.json", "--public-host","acmeat.com"]