apiVersion: v1
kind: PersistentVolume
metadata:
  name: joliebank-mysql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data_joliebank"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joliebank-mysql-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi