apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-restaurant
  namespace: restaurant
  labels:
    app: mysql-restaurant
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql-restaurant
  template:
    metadata:
      namespace: restaurant
      labels:
        app: mysql-restaurant
    spec:
      containers:
        - name: mysql
          image: docker.io/tiesta/asm_restaurant_db:0.15
          ports:
          - containerPort: 3306
            name: mysql
          livenessProbe:
            tcpSocket:
              port: 3306
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

