apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: restaurant
  labels:
    app: mysql-restaurant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi