apiVersion: v1
kind: Service
metadata:
  name: mysql-restaurant
  namespace: restaurant
  labels:
    app: mysql-restaurant
spec:
  type: ClusterIP
  selector:
    app: mysql-restaurant
  ports:
    - port: 3306