apiVersion: v1
kind: Service
metadata:
  name: joliebank-accounts-service
spec:
  type: ClusterIP #OPPURE LoadBalancer
  selector:
    app: joliebank-accounts
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003