apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-restaurant
  labels:
    app: mysql-restaurant
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql-restaurant
  template:
    metadata:
      labels:
        app: mysql-restaurant
    spec:
      containers:
        - name: mysql
          image: docker.io/tiesta/asm_restaurant_db:0.19
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: restaurant-app-cm
                  key: mysql-database-name
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: restaurant-app-cm
                  key: mysql-user-username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: mysql-user-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: mysql-root-password
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: 40
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

