apiVersion: apps/v1

kind: Deployment

metadata:
  name: usermanager
  namespace: default
  labels:
    app: usermanager

spec:
  replicas: 2

  selector:
    matchLabels:
      app: usermanager

  template:
    metadata:
      labels:
        app: usermanager

    spec:
      containers:
        - name: usermanager

          image: docker.io/er4ikk/usermanager
          resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"

          ports:
            - containerPort: 8080
