apiVersion: v1
kind: Service
metadata:
  name: usermanager-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: usermanager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
